name: 🐛 Bug Report
description: Report an issue with the PESU Auth Link Portal
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report

        Thank you for taking the time to report an issue. Please help us diagnose the problem by filling out the following information.
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: 🧵 Bug Summary
      description: Concisely describe the issue you're experiencing.
      placeholder: "e.g. Discord OAuth fails with 'invalid_client' error"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 📋 Steps to Reproduce
      description: Provide a clear set of steps to reproduce the issue.
      placeholder: |
        1. Navigate to the login page at `src/app/login`
        2. Click "Login with Discord"
        3. Complete Discord OAuth flow
        4. Observe the error on redirect
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      placeholder: e.g. "Should redirect to dashboard with user authenticated"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      placeholder: e.g. "Shows 'Authentication failed' error and redirects to login"
    validations:
      required: true

  - type: input
    id: commit
    attributes:
      label: Commit SHA or name
      description: Paste the commit hash or branch name you were using when the bug occurred (e.g. `abc1234`, `main@HEAD`, or `<discord-username>/xyz`).
      placeholder: e.g. abc1234 or <discord-username>/auth-refactor
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: 🧪 Runtime Environment
      description: OS, Node.js version, browser, etc.
      placeholder: e.g. "Windows 11, Node.js 20.x, Chrome 120"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📜 Logs / Traceback
      description: Paste any relevant console logs, error messages, network failures, or `pre-commit` failures.
      render: shell
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: 📁 Area Affected
      multiple: true
      options:
        - Authentication/OAuth
        - User Dashboard
        - Link/Verification Flow
        - API Routes (/api/*)
        - Database/MongoDB
        - Discord Integration
        - UI/Components
        - State Management
        - Middleware
        - Build/Deploy
        - Other
    validations:
      required: true
  
  - type: dropdown
    id: browser
    attributes:
      label: 🌐 Browser (if applicable)
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Browser
        - Multiple Browsers
        - Not Browser Related
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: 🧠 Additional Notes
      description: Add any other context that might help diagnose or prioritize the issue.
    validations:
      required: false